version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        datasource_url: jdbc:postgresql://db:5432/sandbox
        datasource_username: root
        datasource_password: 123
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sandbox
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sandbox